### ISSUE TITLE
Missing Custom.css

### ISSUE THREAD

**Issue by janich** [GavickPro/Portfolio-Free-Joomla-Template#12]
Would it be appropriate to include a 'ready-to-use' custom.css?

**Comment by dziudek** [comment]
We will add the override.css and custom CSS code option in v.1.1 :)

**Comment by janich** [comment]
+1

**Comment by dziudek** [comment]
Done: https://github.com/GavickPro/Portfolio-Free-Joomla-Template/commit/309359c35252b65ab7d70a93c3a03fbd1469bb10
