### ISSUE TITLE
Portfolio boxes stripping tags

### ISSUE THREAD

**Issue by janich** [GavickPro/Portfolio-Free-Joomla-Template#13]
The text in the portfolio boxes (on the frontpage at least) is using the gkExcerpt() function which uses strip_tags(). 

That means, it's impossible to create a box looking like this: http://i.imgur.com/8Px6KTI.png
Imho that's bad.

Why not remove the strip_tags() and take margin-bottom away on the paragraphs in the the boxes, to leave more flexible options for the webmasters?

**Comment by dziudek** [comment]
I will create an option to enable/disable tags stripping, because removing strip_tags function will lead to the HTML parsing errors.

**Comment by janich** [comment]
Yeah, it might break it for some.
Good idea.

**Comment by dziudek** [comment]
Option created: https://github.com/GavickPro/Portfolio-Free-Joomla-Template/commit/65bb508bf64be9009cad8dac1bf24f7144a285dd
