### ISSUE TITLE
Article Share buttons

### ISSUE THREAD

**Issue by eoininho** [GavickPro/Portfolio-Free-Joomla-Template#21]
the share buttons within articles do not copy the link of the article? how can the link be added / the buttons themselves be removed? i cannot find a extension for them and can only remove the icons from the css and not the 'Share' and links themselves.

**Comment by dziudek** [comment]
Unfortunately i.e. in FB it is not possible to provide content for the share.php script, the same in G+. In this case if you need this kind of feature, you have to use some custom 3rd party extensions.

**Comment by eoininho** [comment]
Thank you how do I remove it completely?

Sent from myMail for iOS

Monday, 12 October 2015 19:26 +0100 from Tomasz Dziuda  notifications@github.com:

**Comment by dziudek** [comment]
Please remove this fragment: https://github.com/GavickPro/Portfolio-Free-Joomla-Template/blob/master/html/com_content/article/default.php#L83-L97

**Comment by eoininho** [comment]
thank you

**Comment by eoininho** [comment]
hi

i am unable to remove this piece of code without causing issues to the
tags, i am therefore left with the 'Share:' text any way of removing this
without impacting the tags?

thanks
Eoin

**Comment by dziudek** [comment]
Please install the newest version of the theme v.1.1.1 - there is an option to disable sharing buttons.

**Comment by eoininho** [comment]
thank you I have done some changes to the template which i dont wish t lose. what element of the new version should i look to copy over ? also i only downloaded the quickstart a week ago should that not have the feature you are referring to ?

**Comment by dziudek** [comment]
The changes are visible here: https://github.com/GavickPro/Portfolio-Free-Joomla-Template/commit/5fe6393b727615e11332e44ce075cd130edfd05f the Quickstart was updated last thursday.
