### ISSUE TITLE
Mobile Menu with collapsed submenus?

### ISSUE THREAD

**Issue by cybermarti** [GavickPro/Portfolio-Free-Joomla-Template#23]
Hi there, I'm using the portfolio template for Joomla and I'm wondering if it is possible to collapse the submenus of the mobile menu. It is not really an issue but would be very nice because with many sub and sub/sub menus the mobile menu is getting very looooong and confusing. Any idea? Thanks in advance!

**Comment by dziudek** [comment]
Hello,

I am sorry but it needs a more complex custom work which is beyond of our technical support.
