### ISSUE TITLE
subitem

### ISSUE THREAD

**Issue by 7leo7** [GavickPro/Portfolio-Free-Joomla-Template#30]
Help me, please. I can't put subitem in main menu. http://bashmarina.tmweb.ru/
I want to set pictures like in demo

**Comment by dziudek** [comment]
Hello,

Did you tried to enable submenu display under the menu module which is displayed as a main menu on your website?

**Comment by 7leo7** [comment]
i don't understand where it can be. Could you say me axactly what should i do?

**Comment by dziudek** [comment]
Please read this tutorial: https://docs.joomla.org/J3.x:Creating_a_submenu

**Comment by 7leo7** [comment]
thanks , but i cannot put pictures to main window with portfolio. For menu i can settle picture... here are screenshots
![default](https://cloud.githubusercontent.com/assets/18108743/14195304/d6827232-f7c8-11e5-8147-d377767146f3.png)
![2](https://cloud.githubusercontent.com/assets/18108743/14195306/d688e252-f7c8-11e5-947a-36ccc32bdb9f.png)
![3](https://cloud.githubusercontent.com/assets/18108743/14195305/d6887aec-f7c8-11e5-88d9-69eec9ef2a8a.png)
![default](https://cloud.githubusercontent.com/assets/18108743/14195307/d68a633e-f7c8-11e5-961b-bed7e84112a5.png)

**Comment by dziudek** [comment]
You have to set intro and full image for the articles: https://www.joomla-monster.com/blog/joomla-2-5/how-to-display-intro-and-full-article-images

**Comment by 7leo7** [comment]
thank you!!
