### ISSUE TITLE
Documentation for portfolio images

### ISSUE THREAD

**Issue by tjdesignuk** [GavickPro/Portfolio-Free-Joomla-Template#35]
Hi guys,

I have enabled the template on this page http://www.haversdogbehaviour.co.uk/index.php/dog-owners-knowledge-centre/photography and having a few challenges with the images being displayed for the portfolio. We are using a featured article as per the instructions. Do you have any more detailed documentation I can view please?

Thank you

**Comment by ChronCulture** [comment]
You will find detailed documentation on configuration, module positions or typography in the different menu items of the template demo: https://demo.gavick.com/joomla3/portfolio/index.php

You may find additional information in GavickPro forum: https://www.gavick.com/forums/template-discussion

**Comment by tjdesignuk** [comment]
Thank you for sending the documentation. 

I have read through and I have one question. Can you please let me know
how I would enable the navigation as shown in the example? 

Many thanks for your help. 

On 01-06-2016 15:41, ChronCulture wrote: 

> You will find detailed documentation on configuration, module positions or typography in the different menu items of the template demo: https://demo.gavick.com/joomla3/portfolio/index.php [1] 
> 
> You may find additional information in GavickPro forum: https://www.gavick.com/forums/template-discussion [2] 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].

## 

Many thanks,
 Tracey Johnson 

```
     [5]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [6]
BLOG: www.tjdesignuk.com/design-blog [7] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

## Links:

[1] https://demo.gavick.com/joomla3/portfolio/index.php
[2] https://www.gavick.com/forums/template-discussion
[3]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-223014239
[4]
https://github.com/notifications/unsubscribe/ASprGzX5zsGssMXqhSq8Mc5HjXfOYRUTks5qHZomgaJpZM4Ilvgc
[5] http://www.tjdesignuk.com
[6] http://www.tjdesignuk.com/
[7] http://www.tjdesignuk.com/design-blog

**Comment by dziudek** [comment]
Regarding the menu issue - please read section "Navigation" in this article: https://www.gavick.com/documentation/wordpress/themes/config/wp-portfolio

**Comment by tjdesignuk** [comment]
Thank you. 

Do you have this for the Joomla version rather than WP please? 

On 15-06-2016 22:16, Tomasz Dziuda wrote: 

> Regarding the menu issue - please read section "Navigation" in this article: https://www.gavick.com/documentation/wordpress/themes/config/wp-portfolio [1] 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Many thanks,
 Tracey Johnson 

```
     [4]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [5]
BLOG: www.tjdesignuk.com/design-blog [6] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

Save 

## Links:

[1]
https://www.gavick.com/documentation/wordpress/themes/config/wp-portfolio
[2]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-226322812
[3]
https://github.com/notifications/unsubscribe/ASprG2Ep93UtQLdqdJE586W3PM7RoCS8ks5qMGvEgaJpZM4Ilvgc
[4] http://www.tjdesignuk.com
[5] http://www.tjdesignuk.com/
[6] http://www.tjdesignuk.com/design-blog

**Comment by dziudek** [comment]
Oh, sorry I thought that it is about WP version of this template. For J! version the only article is this one: https://demo.gavick.com/joomla3/portfolio/index.php/features/configuration

But in J! version you have to just create a new menu, then create a module which will use this menu and publish this module at the main-menu module position.

**Comment by tjdesignuk** [comment]
Perfect, thank you so much for your quick response. 

On 15-06-2016 22:35, Tomasz Dziuda wrote: 

> Oh, sorry I thought that it is about WP version of this template. For J! version the only article is this one: https://demo.gavick.com/joomla3/portfolio/index.php/features/configuration [1] 
> 
> But in J! version you have to just create a new menu, then create a module which will use this menu and publish this module at the main-menu module position. 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Many thanks,
 Tracey Johnson 

```
     [4]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [5]
BLOG: www.tjdesignuk.com/design-blog [6] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

Save 

## Links:

[1]
https://demo.gavick.com/joomla3/portfolio/index.php/features/configuration
[2]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-226327260
[3]
https://github.com/notifications/unsubscribe/ASprGxtXwUf_d8wB6BY0gL-idb_6HIYVks5qMHAIgaJpZM4Ilvgc
[4] http://www.tjdesignuk.com
[5] http://www.tjdesignuk.com/
[6] http://www.tjdesignuk.com/design-blog

**Comment by tjdesignuk** [comment]
Hi Tomasz, 

Sorry - one final question I promise! 

I have enable the portfolio style template on three page of a site but
having trouble getting the home page link to click back to
http://www.haversdogbehaviour.co.uk/index.php/dog-owners-knowledge-centre/photography

Would you happen to know which menu type and title to use for the menu
to get the link to work? 

Thanks so much for your help, 

Tracey 

On 15-06-2016 22:35, Tomasz Dziuda wrote: 

> Oh, sorry I thought that it is about WP version of this template. For J! version the only article is this one: https://demo.gavick.com/joomla3/portfolio/index.php/features/configuration [1] 
> 
> But in J! version you have to just create a new menu, then create a module which will use this menu and publish this module at the main-menu module position. 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Many thanks,
 Tracey Johnson 

```
     [4]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [5]
BLOG: www.tjdesignuk.com/design-blog [6] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

## Links:

[1]
https://demo.gavick.com/joomla3/portfolio/index.php/features/configuration
[2]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-226327260
[3]
https://github.com/notifications/unsubscribe/ASprGxtXwUf_d8wB6BY0gL-idb_6HIYVks5qMHAIgaJpZM4Ilvgc
[4] http://www.tjdesignuk.com
[5] http://www.tjdesignuk.com/
[6] http://www.tjdesignuk.com/design-blog

**Comment by tjdesignuk** [comment]
Hi Tomasz, 

Sorry - this is the final one! 

I have been having a play around with the number of columns in the
layout section but nothing seems to change on the home page according to
the documentation... 

http://www.haversdogbehaviour.co.uk/index.php/dog-owners-knowledge-centre/photography

Can you point me in the right direction please 

Thank you 

On 15-06-2016 22:35, Tomasz Dziuda wrote: 

> Oh, sorry I thought that it is about WP version of this template. For J! version the only article is this one: https://demo.gavick.com/joomla3/portfolio/index.php/features/configuration [1] 
> 
> But in J! version you have to just create a new menu, then create a module which will use this menu and publish this module at the main-menu module position. 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Many thanks,
 Tracey Johnson 

```
     [4]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [5]
BLOG: www.tjdesignuk.com/design-blog [6] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

## Links:

[1]
https://demo.gavick.com/joomla3/portfolio/index.php/features/configuration
[2]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-226327260
[3]
https://github.com/notifications/unsubscribe/ASprGxtXwUf_d8wB6BY0gL-idb_6HIYVks5qMHAIgaJpZM4Ilvgc
[4] http://www.tjdesignuk.com
[5] http://www.tjdesignuk.com/
[6] http://www.tjdesignuk.com/design-blog

**Comment by dziudek** [comment]
@tjdesignuk - could you better explain your issues? Because your description is not clear for me.

**Comment by tjdesignuk** [comment]
Hi Tomasz, 

Sure - I have added my questions to the screenshot below... 

The link to the page is
http://www.haversdogbehaviour.co.uk/index.php/dog-owners-knowledge-centre/photography

Many thanks for your help. 

On 20-06-2016 10:07, Tomasz Dziuda wrote: 

> @tjdesignuk [1] - could you better explain your issues? Because your description is not clear for me. 
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Many thanks,
 Tracey Johnson 

```
     [4]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [5]
BLOG: www.tjdesignuk.com/design-blog [6] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

## Links:

[1] https://github.com/tjdesignuk
[2]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-227088493
[3]
https://github.com/notifications/unsubscribe/ASprG9P6WDm2KpL6Jl6Cuc23N02eXDWzks5qNlhKgaJpZM4Ilvgc
[4] http://www.tjdesignuk.com
[5] http://www.tjdesignuk.com/
[6] http://www.tjdesignuk.com/design-blog

**Comment by dziudek** [comment]
Please try to send the image as a link, because I do not see it.

**Comment by tjdesignuk** [comment]
Hi Tomasz, 

I have attached the link to this email and you can view this here...
http://www.tjdesignuk.com/downloads/portfolio-changes.jpg [3] 

Many thanks, 

Tracey 

On 21-06-2016 13:30, Tomasz Dziuda wrote: 

> Please try to send the image as a link, because I do not see it. 
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

## 

Many thanks,
 Tracey Johnson 

PLEASE NOTE: I WILL BE ON ANNUAL LEAVE FROM THE 29TH JUNE RETURNING ON
THE 14TH JULY 

```
     [4]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [5]
BLOG: www.tjdesignuk.com/design-blog [6] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

## Links:

[1]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-227424949
[2]
https://github.com/notifications/unsubscribe/ASprG5ZS8RxK33z2TEdemKUr-GiTQhqLks5qN9lvgaJpZM4Ilvgc
[3] http://www.tjdesignuk.com/downloads/portfolio-changes.jpg%20
[4] http://www.tjdesignuk.com
[5] http://www.tjdesignuk.com/
[6] http://www.tjdesignuk.com/design-blog

**Comment by dziudek** [comment]
1. Please remove a link around the highlighted code fragment: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/blob/master/header.php#L24-L33
2. The easiest way is create an external link which will be a link to a specific page in your domain
3. In the theme customizer you can change amount of columns - section "Layout and Features"

**Comment by tjdesignuk** [comment]
Hi Tomasz, 

Thank you for getting back to me. Can you please send this for Joomla -
not Wordpress. 

Many thanks, 

On 23-06-2016 07:41, Tomasz Dziuda wrote: 

> - 
> 
> Please remove a link around the highlighted code fragment: https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/blob/master/header.php#L24-L33 [1] 
> - 
> 
> The easiest way is create an external link which will be a link to a specific page in your domain 
> - 
> 
> In the theme customizer you can change amount of columns - section "Layout and Features" 
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Many thanks,
 Tracey Johnson 

PLEASE NOTE: I WILL BE ON ANNUAL LEAVE FROM THE 29TH JUNE RETURNING ON
THE 14TH JULY 

```
     [4]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [5]
BLOG: www.tjdesignuk.com/design-blog [6] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

Save 

## Links:

[1]
https://github.com/GavickPro/Portfolio-Free-WordPress-Theme/blob/master/header.php#L24-L33
[2]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-227963445
[3]
https://github.com/notifications/unsubscribe/ASprGzLtjOkL6eARfLQpja8o4fgWjiP0ks5qOiq0gaJpZM4Ilvgc
[4] http://www.tjdesignuk.com
[5] http://www.tjdesignuk.com/
[6] http://www.tjdesignuk.com/design-blog

**Comment by dziudek** [comment]
1. Please remove a link around the highlighted code fragment: https://github.com/GavickPro/Portfolio-Free-Joomla-Template/blob/master/inc/layout.php#L56-L65
2. It is the same as for WP
3. The columns number is available to set in the menu item settings for a category/featured items blog

**Comment by tjdesignuk** [comment]
Hi Tomasz, 

Thank you for this. Please see my comments below... 

```
* 
```

Please remove a link around the highlighted code fragment:
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/blob/master/inc/layout.php#L56-L65

Done - thank you 
    \* 

It is the same as for WP 

Done - thank you 
    \* 

The columns number is available to set in the menu item settings for a
category/featured items blog 

I have been able to edit the number of columns on this page
http://www.haversdogbehaviour.co.uk/index.php/dog-owners-knowledge-centre/photography
[4] but i'm not sure if there is a bug as there is a gap where the last
two photos should be on each view.

On 24-06-2016 06:27, Tomasz Dziuda wrote: 

> - 
> 
> Please remove a link around the highlighted code fragment: https://github.com/GavickPro/Portfolio-Free-Joomla-Template/blob/master/inc/layout.php#L56-L65 [1] 
> - 
> 
> It is the same as for WP 
> - 
> 
> The columns number is available to set in the menu item settings for a category/featured items blog 
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Many thanks,
 Tracey Johnson 

PLEASE NOTE: I WILL BE ON ANNUAL LEAVE FROM THE 29TH JUNE RETURNING ON
THE 14TH JULY 

```
     [5]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [6]
BLOG: www.tjdesignuk.com/design-blog [7] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

Save 

## Links:

[1]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/blob/master/inc/layout.php#L56-L65
[2]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-228261143
[3]
https://github.com/notifications/unsubscribe/ASprG8X8TM4wBTy22C2BNBHI_hRg8pujks5qO2rTgaJpZM4Ilvgc
[4]
http://www.haversdogbehaviour.co.uk/index.php/dog-owners-knowledge-centre/photography
[5] http://www.tjdesignuk.com
[6] http://www.tjdesignuk.com/
[7] http://www.tjdesignuk.com/design-blog

**Comment by dziudek** [comment]
Please try to set your columns like below:

![columns](https://cloud.githubusercontent.com/assets/22004/16407180/b0470ef4-3d12-11e6-827d-4e7f933224f6.png)

**Comment by tjdesignuk** [comment]
Thanks very much. Perfect 

On 28-06-2016 08:28, Tomasz Dziuda wrote: 

> Please try to set your columns like below: 
> 
> [1] 
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Many thanks,
 Tracey Johnson 

PLEASE NOTE: I WILL BE ON ANNUAL LEAVE FROM THE 29TH JUNE RETURNING ON
THE 14TH JULY 

```
     [4]
```

 TJ DESIGN UK
 PHONE: 07855 713 178
 EMAIL: tracey@tjdesignuk.com
 WEBSITE: www.tjdesignuk.com [5]
BLOG: www.tjdesignuk.com/design-blog [6] 

This e-mail and the information contained herein is intended for the
named recipient(s) only and is confidential information. Any disclosure,
copying, distribution or use of its contents is prohibited. Any views or
opinions presented in the email are solely the views of the author and
may not represent the views of TJ Design UK. TJ Design UK cannot accept
responsibility for any loss or damage arising from the use of this email
or attachments. If you no longer wish to receive communication from TJ
Design UK please return this email to the sender or notify us by email
at info@tjdesignuk.com 

Save 

## Links:

[1]
https://cloud.githubusercontent.com/assets/22004/16407180/b0470ef4-3d12-11e6-827d-4e7f933224f6.png
[2]
https://github.com/GavickPro/Portfolio-Free-Joomla-Template/issues/35#issuecomment-228972759
[3]
https://github.com/notifications/unsubscribe/ASprGxJdwkw-A1q0NgVjDhX6kXWkZKEhks5qQM0ngaJpZM4Ilvgc
[4] http://www.tjdesignuk.com
[5] http://www.tjdesignuk.com/
[6] http://www.tjdesignuk.com/design-blog
