### ISSUE TITLE
Menu behind content

### ISSUE THREAD

**Issue by hurradiegams** [GavickPro/Portfolio-Free-Joomla-Template#38]
Hi there,

I am greatly satisfied with your template, but found one bug:
the menu (including submenus) disappears behind the content under some circumstances, this only seems to happen in combination with Phoca Gallery.

But I can't find any relevant informations in the module or the Phoca Help Team, it's considered to be a problem with the template.
Everything boils down to adjusting/setting the z-index, but I can't find the right file/line/position to add the relevant value.

Any support on this would be highly appreciated, thanks you for your work :)

**Comment by dziudek** [comment]
Hi,

Please provide an URL to your website with this problem visible.

**Comment by hurradiegams** [comment]
Thank you for your fast reply, this is the site in question: http://dazzekammerl.de/index.php/home/bilder/grafik

If you hover over "Start" the menu opens, but you can't se the menu-points behind the pictures (the menu behaves normally on any other site, except on a different contactform I've had earlier, same behaviour).

**Comment by dziudek** [comment]
Please try to add the following code:

``` css
.navigation {
    position: relative;
}
```

**Comment by hurradiegams** [comment]
I've added the code to the "Custom CSS Code" section in "Advanced" in the template settings (and it does show up in the source code of the site after saving and reloading), but sadly the menu is still partly hidden behind the pictures.

Edit: I've got it by adding the following code:

``` css
.navigation {
    position: relative;
    z-index: 999;
}
```

I'll try to persuade the owner of the website to get at least your single-prescription, thanks a million for your great work :)
